---
# TODO: Find a way to create a temp AWX, create a token with awx.awx collection and test integration
# - name: Create the tower.ansible.com/v1alpha1.JobTemplate
#   k8s:
#     state: present
#     namespace: '{{ namespace }}'
#     definition: "{{ lookup('template', '/'.join([samples_dir, cr_file])) | from_yaml }}"
#     wait: yes
#     wait_timeout: 300
#     wait_condition:
#       type: Running
#       reason: Successful
#       status: "True"
#   vars:
#     cr_file: 'tower_v1alpha1_jobtemplate.yaml'

# TODO: Remove once CI is fully added
- name: Add assertions here
  assert:
    that: true
    fail_msg: FIXME Add real assertions for your operator
