apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ meta.name }}"
  namespace: "{{ meta.namespace }}"
spec:
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      serviceAccountName: tower-resource-operator
      containers:
      - name: joblaunch
        image: matburt/operator-job-run:latest
        env:
          - name: TOWER_OAUTH_TOKEN
            value: "{{ tower_config_secret['resources'][0]['data']['token'] | b64decode }}"
          - name: TOWER_HOST
            value: "{{ tower_config_secret['resources'][0]['data']['host'] | b64decode }}"
          - name: TOWER_JOB_TEMPLATE_NAME
            value: "{{ job_template_name }}"
          - name: TOWER_VERIFY_SSL
            value: "False"
          - name: ANSIBLEJOB_NAME
            value: "{{ meta.name }}"
          - name: ANSIBLEJOB_NAMESPACE
            value: "{{ meta.namespace }}"
      restartPolicy: Never
  backoffLimit: 1