---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ansiblejobs.tower.ansible.com
spec:
  group: tower.ansible.com
  names:
    kind: AnsibleJob
    listKind: AnsibleJobList
    plural: ansiblejobs
    singular: ansiblejob
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
        description: Schema validation for the Tower Job Launch CRD
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              tower_auth_secret:
                type: string
              job_template_name:
                type: string
              inventory:
                type: string
              extra_vars:
                description: extra_vars is a JSON string. For example,
                  '{"version":"1.23.45","other_variable":"foo","pacman":"mrs","ghosts":["inky","pinky","clyde","sue"]}'
                type: string
            required:
            - tower_auth_secret
            type: object
    served: true
    storage: true
    subresources:
      status: {}
