# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/tower.ansible.com_ansiblejobs.yaml
- bases/tower.ansible.com_jobtemplates.yaml
- bases/tower.ansible.com_ansibleprojects.yaml
- bases/tower.ansible.com_ansibleworkflows.yaml
- bases/tower.ansible.com_ansiblecredentials.yaml
- bases/tower.ansible.com_ansibleschedules.yaml
- bases/tower.ansible.com_ansibleinstancegroups.yaml
- bases/tower.ansible.com_workflowtemplates.yaml
- bases/tower.ansible.com_ansibleinventories.yaml
- bases/tower.ansible.com_ansibleexecutionenvironments.yaml
#+kubebuilder:scaffold:crdkustomizeresource
